# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###  登录
GET http://qk.heniankj.com/public/index.php/home/teacher/login?username=wj&password=123456
#Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest


### 注册
POST http://qk.heniankj.com/public/index.php/home/teacher/register
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest

### select
GET http://qk.heniankj.com/public/index.php/home/teacher/getInfo
#Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest

### changePasswd
GET http://qk.heniankj.com/public/index.php/home/teacher/changePasswd
#Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest

### 获取课程列表
GET http://qk.heniankj.com/public/index.php/home/teacher/getCourse
#Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest

### 提交用户的新信息
GET http://qk.heniankj.com/public/index.php/home/teacher/changeInfo?id=13
#Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest

###
GET http://qk.heniankj.com/public/index.php/home/teacher/getCourse?id=13
X-Requested-With: XMLHttpRequest

###
GET http://qk.heniankj.com/public/index.php/home/coursedetail/getdetailbyid/id/4
X-Requested-With: XMLHttpRequest

###


